AWSTemplateFormatVersion: '2010-09-09'
Description: Hands-on 04 step 05 CloudFront stack

Parameters:
  ProjectName:
    Type: String
    Default: handson-04
  AlbStackName:
    Type: String
    Default: handson-03-alb

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub ${ProjectName} distribution
        DefaultCacheBehavior:
          TargetOriginId: alb-origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3
        DefaultRootObject: ''
        HttpVersion: http2
        Origins:
          - Id: alb-origin
            DomainName: !ImportValue
              Fn::Sub: ${AlbStackName}-LoadBalancerDnsName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        PriceClass: PriceClass_200
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: !Sub ${AWS::StackName}-CloudFrontDomainName
